<?php use App\Framework\UserSession;?>

<nav class="Header-Navbar">
    <div class="Header-Navbar-menu">
        <span class="Header-Navbar-menu-cross" id="cross">✖</span>
        <ul class="Header-Navbar-menu-list">
            <li class="Header-Navbar-menu-list-item">
                <a class="Header-Navbar-menu-list-item-link" href="">À propos</a>
            </li>
            <li class="Header-Navbar-menu-list-item">
                <a class="Header-Navbar-menu-list-item-link" href="">Rechercher</a>
            </li>

            <?php if(UserSession::isAuthenticated()):?>

                <li class="Header-Navbar-menu-list-item">
                    <a class="Header-Navbar-menu-list-item-link" href="<?=buildUrl('dashboard');?>">Administration</a>
                </li>
                <li class="Header-Navbar-menu-list-item">
                    <a class="Header-Navbar-menu-list-item-link" href="<?=buildUrl('dashboard');?>">Bonjour <?=UserSession::getFullname();?></a>
                </li>
                <li class="Header-Navbar-menu-list-item">
                    <a class="Header-Navbar-menu-list-item-link" href="<?=buildUrl('logout');?>">Déconnexion</a>
                </li>

            <?php else:?>

                <li class="Header-Navbar-menu-list-item">
                    <a class="Header-Navbar-menu-list-item-link" href="<?=buildUrl('login');?>">Connexion</a>
                </li>
                <li class="Header-Navbar-menu-list-item">
                    <a class="Header-Navbar-menu-list-item-link" href="<?=buildUrl('signup');?>">Inscription</a>
                </li>

            <?php endif;?>
            
        </ul>
    </div>
    <span class="Header-Navbar-burger" id="burger">☰</span>
</nav>