<div class="Admin">
    <h2 class="Admin-title">Modifier mes informations personnelles</h2>
    <form action="<?=buildUrl('personal-informations');?>" method="post" class="Form">
            <div class="Form-component">
                <input class="Form-component-input" type="text" name="lastname" value="<?=$lastname;?>" placeholder="Nom" maxlength="50" required>
            </div>
            <div class="Form-component">
                <input class="Form-component-input" type="text" name="firstname" value="<?=$firstname;?>" placeholder="Prénom" maxlength="50" required>
            </div>
            <div class="Form-component">
                <input class="Form-component-input" type="text" name="pseudo" value="<?=$pseudo;?>" placeholder="Pseudo" maxlength="50" required>
            </div>
            <div class="Form-component">
                <input class="Form-component-input" type="email" name="email" value="<?=$email;?>" placeholder="E-mail" maxlength="50" required>
            </div>
            <div class="Form-component">
            <input type="hidden" name="checkToken" value="<?=$token;?>">
        </div>
            <input type="submit" class="Form-button" value="Modifier mes informations">
        </form>
</div>