<div class="Account">
    <h2 class="Account-title">Connexion</h2>

    <?php if(!$isLogged):?>

        <form action="<?=buildUrl('login');?>" method="post" class="Form">
            <div class="Form-component">
                <input class="Form-component-input" type="email" name="email" value="<?=$email;?>" placeholder="E-mail" maxlength="50" required>
            </div>
            <div class="Form-component">
                <input class="Form-component-input" type="password" id="inputPassword" name="password" value="" placeholder="Mot de passe" maxlength="50" required>
            </div>
            <input type="submit" class="Form-button" value="Se connecter">
        </form>
        
    <?php else :?>

        <p>Vous êtes déjà connecté</p>

    <?php endif;?>

</div>