<div class="MenuAdmin">
    <h3 class="MenuAdmin-title">Menu</h3>
    <ul class="MenuAdmin-list">
    <li class="MenuAdmin-list-item">
            <a class="MenuAdmin-list-item-link" href="<?=buildUrl('dashboard');?>">Tableau de bord</a>
        </li>
        <li class="MenuAdmin-list-item">
            <a class="MenuAdmin-list-item-link" href="">Nouvel article</a>
        </li>
        <li class="MenuAdmin-list-item">
            <a class="MenuAdmin-list-item-link" href="<?=buildUrl('articles');?>">Mes articles</a>
        </li>
        <li class="MenuAdmin-list-item">
            <a class="MenuAdmin-list-item-link" href="<?=buildUrl('logout');?>" >Se déconnecter</a>
        </li>
    </ul>
</div>