<div class="Page">
    <h2 class="Page-title">Rechercher un article</h2>
    <form action="<?=buildUrl('search-article');?>" method="post" class="Form">
        <div class="Form-component">
            <input class="Form-component-input" type="text" name="search" value="" placeholder="Rechercher un article" maxlength="50" required>
        </div>
        <input type="submit" class="Form-button" value="Rechercher">
    </form>
    <div class="Page-articles">
    </div>

</div>

<script src="<?=asset('js/article/SearchArticleManager.js');?>"></script>