<div class="Signup">
    <h2 class="Signup-title">Inscription</h2>
    <form action="<?=buildUrl('signup');?>" method="post" class="Form">
        <div class="Form-component">
            <input class="Form-component-input" type="text" name="lastname" value="<?=$lastname;?>" placeholder="Nom" maxlength="50" required>
        </div>
        <div class="Form-component">
            <input class="Form-component-input" type="text" name="firstname" value="<?=$firstname;?>" placeholder="Prénom" maxlength="50" required>
        </div>
        <div class="Form-component">
            <input class="Form-component-input" type="text" name="pseudo" value="<?=$pseudo;?>" placeholder="Pseudo" maxlength="50"required>
        </div>
        <div class="Form-component">
            <input class="Form-component-input" type="email" name="email" value="<?=$email;?>" placeholder="E-mail" maxlength="50" required>
        </div>
        <div class="Form-component">
            <input class="Form-component-input" type="password" id="inputPassword" name="password" value="" placeholder="Mot de passe" maxlength="50" required>
            <input type="button" class="Form-component-button" id="showPassword" value="Voir">
        </div>
        <div class="Form-component">
            <input class="Form-component-input" type="password" name="confirmPassword" value="" placeholder="Confirmer" maxlength="50" required>
        </div>
        <input type="submit" class="Form-button" value="S'inscrire">
    </form>
</div>

<script src="<?=asset('js/signup/PasswordManager.js');?>"></script>